Development
Urchmaney/Backgrounds-and-Gradients pull request #1
Opened 2019-07-12 22:48 UTC by Urchmaney

Requesting pull request

2019-07-15 12:50 UTC, Torres-ssf commented
- [ ]  There are some errors in your CSS code. Check them using this CSS [validator](https://jigsaw.w3.org/css-validator/) . Ignore the warnings.

- [ ] Try to make your page fit the full width of the page(like the original one):
![image](https://user-images.githubusercontent.com/30977845/61217400-fe8ebe00-a6e5-11e9-8fbc-57bb11b200dd.png)


#### Navbar

- [ ] It's best practice to use the `nav` tag for the navbar.

#### Main content links(The 3 main sentences)

- [ ] There should be three links
- [ ] Each link is an `a` HTML tag, with a `div` tag inside it.
- [ ] The `div` tag inside the `a` tag should use an image as background. The text on the original page is actually an image
- [ ] It's best practice to the `main` tag for the main content of your page.

#### Footer

- [ ] The footer must start at the 4 iphone promo images(top part of the footer)
- [ ] The top part is made of four `a` tags with `div` tags inside it
- [ ] The `div`s inside the `a` tags should use an image as a background

2019-07-16 13:36 UTC, Ispirett requested changes
Hey @Urchmaney  great work fixing the issues form you last **PR**  your site really looks gorgeous :100: 
However there are  still some issues that need addressing.
 - [ ] The search field should be an <input> HTML tag with the focus effect enabled

2019-07-16 13:36 UTC, Ispirett commented on index.html
> +                    <ul id="nav-bar">
You should use floats or display: flex for this section instead of inline-block

2019-07-16 13:36 UTC, Ispirett commented on index.html
> +        <div id="footer">
Use a footer tag instead of a div here

2019-07-16 13:36 UTC, Ispirett commented on index.html
> +    <div id="container">
Use the main tag instead of div here

2019-07-17 12:28 UTC, Torres-ssf commented
### Great work 👏
You can merge to master now. Don't forget to submit the form. Good luck with the next project

2019-07-17 13:37 UTC, merged